config/routes.rb
Rails.application.routes.draw do

       root 'pages#home'
       get 'about', to: 'pages#about'
       resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true, length: {minimum: 3, maximum: 50}
	validates :description, presence: true,  length: {minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def new
		@article = Article.new
	end

	def create
		# render plain: params[:article].inspect
		@article = Article.new(article_params)
		@article.save
		redirect_to articles_show(@article)
	end

	private
	def article_params
		params.require(:article).permit(:title, :description)
		
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end

	def about
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/new.html.erb
<h1>Create an Article</h1>

<%= form_for @article do |f| %>
	<p>
		<%= f.label :title %><br/>
		<%= f.text_field :title %>
	</p>
	
	<p>
		<%= f.label :description %><br/>
		<%= f.text_area :description %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<h1>Welcome to</h1>
<h2>The Alpha Blog</h2>


Links<br>

<ul>

<li><%= link_to "About", about_path %></li>
<li><%= link_to "Undefined Link", about_path %></li>

</ul>




<h6>Copyright ONYX Design Space@2015</h6>